name: Translations

on:
  push:
    branches:
      - master

jobs:
  plugin_dst:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install qgis-plugin-ci
        run: pip3 install qgis-plugin-ci

      # When osgeo upload is wanted: --osgeo-username usrname --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
      - name: Push translations
        run: qgis-plugin-ci push-translation ${{ secrets.TRANSIFEX_TOKEN }}
