name: Release

on:
  release:
    types: published

jobs:
  plugin_dst:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Qt lrelease
        run: sudo apt-get install qt5-default qttools5-dev-tools

      - name: Install qgis-plugin-ci
        run: pip3 install qgis-plugin-ci

      - name: Deploy plugin
        run: qgis-plugin-ci release ${GITHUB_REF/refs\/tags\//} --github-token ${{ secrets.GITHUB_TOKEN }} --osgeo-username Joonala --osgeo-password ${{ secrets.OSGEO_PASSWORD }} --transifex-token ${{ secrets.TRANSIFEX_TOKEN }} --disable-submodule-update
